const fs = require('fs');
const path = require('path');

const DATASET_PATH = path.join(__dirname, '..', 'data', 'exercises-dataset', 'data', 'exercises.json');
const CATALOG_OUT = path.join(__dirname, '..', 'data', 'exercises.catalog.json');
const ALIASES_OUT = path.join(__dirname, '..', 'data', 'exercise-aliases.it.json');

// Mappa italiana curata per i casi più comuni. Gli altri esercizi rimangono con canonicalIt vuoto.
const ITALIAN_MAPPINGS = {
  '3/4 sit-up': { canonicalIt: 'Sit-up 3/4', aliases: ['sit-up parziale', 'crunch 3/4'] },
  '45° leg press': { canonicalIt: 'Leg press 45°', aliases: ['leg press', 'pressa 45', 'pressa a 45'] },
  'ab crunch machine': { canonicalIt: 'Crunch alla macchina', aliases: ['crunch macchina', 'ab crunch'] },
  'alternate heel touchers': { canonicalIt: 'Tocchi alternati ai talloni', aliases: ['heel touch', 'tocchi talloni'] },
  'alternate lateral pulldown': { canonicalIt: 'Pulldown laterale alternato', aliases: ['pulldown alternato'] },
  'arm slingers hanging bent knee legs': { canonicalIt: 'Sollevamento ginocchia piegate in sospensione', aliases: ['knee raise sospensione'] },
  'assisted chest dip (kneeling)': { canonicalIt: 'Dip petto assistito in ginocchio', aliases: ['dip petto assistito'] },
  'assisted parallel close grip pull-up': { canonicalIt: 'Pull-up presa stretta assistita', aliases: ['pull up stretta assistita'] },
  'assisted pull-up': { canonicalIt: 'Pull-up assistita', aliases: ['pull up assistita', 'pullup assistito'] },
  'assisted standing chin-up': { canonicalIt: 'Chin-up assistito in piedi', aliases: ['chin up assistito'] },
  'assisted standing triceps extension (with towel)': { canonicalIt: 'Extension tricipiti in piedi assistita con asciugamano', aliases: ['extension tricipiti asciugamano'] },
  'back extension': { canonicalIt: 'Iperextensione lombare', aliases: ['iperextensione', 'back extension panca'] },
  'back lever': { canonicalIt: 'Back lever', aliases: ['leva posteriore'] },
  'band alternating biceps curl': { canonicalIt: 'Curl bicipiti alternato con elastico', aliases: ['curl elastico alternato'] },
  'band assisted pull-up': { canonicalIt: 'Pull-up assistita con elastico', aliases: ['pull up elastico'] },
  'band bench press': { canonicalIt: 'Panca piana con elastico', aliases: ['bench press elastico'] },
  'band bent-over hip extension': { canonicalIt: 'Extension fianchi piegato con elastico', aliases: ['hip extension elastico'] },
  'band biceps curl': { canonicalIt: 'Curl bicipiti con elastico', aliases: ['curl elastico'] },
  'band close-grip pulldown': { canonicalIt: 'Pulldown presa stretta con elastico', aliases: ['pulldown stretto elastico'] },
  'band deadlift': { canonicalIt: 'Stacco da terra con elastico', aliases: ['deadlift elastico'] },
  'band front lateral raise': { canonicalIt: 'Alzate frontali laterali con elastico', aliases: ['lateral raise elastico'] },
  'band hip pull-through': { canonicalIt: 'Hip pull-through con elastico', aliases: ['pull through elastico'] },
  'band horizontal rear neck traction': { canonicalIt: 'Trazione posteriore collo orizzontale con elastico', aliases: ['neck traction elastico'] },
  'band one arm single leg split squat': { canonicalIt: 'Bulgarian split squat monobraccio con elastico', aliases: ['split squat elastico'] },
  'band pull apart': { canonicalIt: 'Pull apart con elastico', aliases: ['pull apart'] },
  'band reverse fly': { canonicalIt: 'Reverse fly con elastico', aliases: ['reverse fly elastico'] },
  'band reverse wrist curl': { canonicalIt: 'Reverse wrist curl con elastico', aliases: ['reverse curl polsi elastico'] },
  'band seated hip internal rotation': { canonicalIt: 'Rotazione interna anca seduto con elastico', aliases: ['hip rotation elastico'] },
  'band shoulder press': { canonicalIt: 'Shoulder press con elastico', aliases: ['military press elastico'] },
  'band shrug': { canonicalIt: 'Shrug con elastico', aliases: ['shrug elastico'] },
  'band standing crunch': { canonicalIt: 'Crunch in piedi con elastico', aliases: ['crunch in piedi elastico'] },
  'band straight back stiff leg deadlift': { canonicalIt: 'Stiff leg deadlift con elastico', aliases: ['stiff elastico'] },
  'band sumo deadlift': { canonicalIt: 'Sumo deadlift con elastico', aliases: ['sumo deadlift elastico'] },
  'band triceps extension': { canonicalIt: 'Extension tricipiti con elastico', aliases: ['extension tricipiti elastico'] },
  'band twist': { canonicalIt: 'Twist con elastico', aliases: ['rotazione busto elastico'] },
  'band wrist curl': { canonicalIt: 'Wrist curl con elastico', aliases: ['curl polsi elastico'] },
  'barbell bench press': { canonicalIt: 'Panca piana con bilanciere', aliases: ['panca piana', 'distensioni su panca piana', 'bench press bilanciere', 'panca'] },
  'barbell bent arm pullover': { canonicalIt: 'Pullover con braccia piegate con bilanciere', aliases: ['pullover bilanciere'] },
  'barbell bent over row': { canonicalIt: 'Rematore con bilanciere', aliases: ['bent over row bilanciere', 'rematore'] },
  'barbell biceps curl': { canonicalIt: 'Curl bicipiti con bilanciere', aliases: ['curl bilanciere', 'curl bb'] },
  'barbell clean and press': { canonicalIt: 'Clean and press con bilanciere', aliases: ['clean and press'] },
  'barbell close-grip bench press': { canonicalIt: 'Panca stretta con bilanciere', aliases: ['panca stretta', 'close grip bench press'] },
  'barbell curl': { canonicalIt: 'Curl bicipiti con bilanciere', aliases: ['curl bilanciere'] },
  'barbell deadlift': { canonicalIt: 'Stacco da terra con bilanciere', aliases: ['deadlift bilanciere', 'stacco'] },
  'barbell decline bench press': { canonicalIt: 'Panca declinata con bilanciere', aliases: ['panca declinata', 'decline bench press'] },
  'barbell decline pullover': { canonicalIt: 'Pullover declinato con bilanciere', aliases: ['pullover declinato'] },
  'barbell decline wide-grip press': { canonicalIt: 'Panca declinata presa larga con bilanciere', aliases: ['decline press larga'] },
  'barbell floor press': { canonicalIt: 'Floor press con bilanciere', aliases: ['floor press'] },
  'barbell front raise': { canonicalIt: 'Alzate frontali con bilanciere', aliases: ['front raise bilanciere'] },
  'barbell full squat': { canonicalIt: 'Squat completo con bilanciere', aliases: ['squat bilanciere', 'squat'] },
  'barbell glute bridge': { canonicalIt: 'Glute bridge con bilanciere', aliases: ['ponte glutei bilanciere'] },
  'barbell good morning': { canonicalIt: 'Good morning con bilanciere', aliases: ['good morning'] },
  'barbell hack squat': { canonicalIt: 'Hack squat con bilanciere', aliases: ['hack squat bilanciere'] },
  'barbell hip thrust': { canonicalIt: 'Hip thrust con bilanciere', aliases: ['hip thrust bilanciere'] },
  'barbell incline bench press': { canonicalIt: 'Panca inclinata con bilanciere', aliases: ['panca inclinata', 'incline bench press bilanciere'] },
  'barbell incline row': { canonicalIt: 'Rematore inclinato con bilanciere', aliases: ['incline row bilanciere'] },
  'barbell incline shoulder raise': { canonicalIt: 'Alzate spalle inclinate con bilanciere', aliases: ['shoulder raise bilanciere'] },
  'barbell jefferson squat': { canonicalIt: 'Jefferson squat con bilanciere', aliases: ['jefferson squat'] },
  'barbell jump squat': { canonicalIt: 'Jump squat con bilanciere', aliases: ['squat salto bilanciere'] },
  'barbell lunge': { canonicalIt: 'Affondi con bilanciere', aliases: ['affondi bilanciere', 'lunge bilanciere'] },
  'barbell lying close-grip triceps extension': { canonicalIt: 'Extension tricipiti disteso presa stretta con bilanciere', aliases: ['skullcrusher stretto', 'french press stretto'] },
  'barbell lying extension': { canonicalIt: 'Extension tricipiti disteso con bilanciere', aliases: ['skullcrusher', 'french press'] },
  'barbell lying preacher curl': { canonicalIt: 'Curl su panca Scott distesa con bilanciere', aliases: ['preacher curl bilanciere'] },
  'barbell lying triceps extension': { canonicalIt: 'Extension tricipiti disteso con bilanciere', aliases: ['lying triceps extension'] },
  'barbell military press': { canonicalIt: 'Military press con bilanciere', aliases: ['shoulder press bilanciere', 'spinte bilanciere'] },
  'barbell one arm bent row': { canonicalIt: 'Rematore monobraccio con bilanciere', aliases: ['one arm row bilanciere'] },
  'barbell one arm floor press': { canonicalIt: 'Floor press monobraccio con bilanciere', aliases: ['floor press monobraccio'] },
  'barbell one arm snatch': { canonicalIt: 'Snatch monobraccio con bilanciere', aliases: ['one arm snatch'] },
  'barbell overhead squat': { canonicalIt: 'Overhead squat con bilanciere', aliases: ['squat sopra testa'] },
  'barbell pin squats': { canonicalIt: 'Pin squat con bilanciere', aliases: ['pin squat'] },
  'barbell preacher curl': { canonicalIt: 'Curl su panca Scott con bilanciere', aliases: ['preacher curl', 'curl scott'] },
  'barbell press': { canonicalIt: 'Spinte in piedi con bilanciere', aliases: ['spinte bilanciere'] },
  'barbell pullover': { canonicalIt: 'Pullover con bilanciere', aliases: ['pullover'] },
  'barbell pullover to press': { canonicalIt: 'Pullover to press con bilanciere', aliases: ['pullover press'] },
  'barbell rack pull': { canonicalIt: 'Rack pull con bilanciere', aliases: ['rack pull'] },
  'barbell rear delt raise': { canonicalIt: 'Alzate deltoidi posteriori con bilanciere', aliases: ['rear delt raise bilanciere'] },
  'barbell rear delt row': { canonicalIt: 'Rematore deltoidi posteriori con bilanciere', aliases: ['rear delt row'] },
  'barbell reverse curl': { canonicalIt: 'Curl inverso con bilanciere', aliases: ['reverse curl bilanciere'] },
  'barbell reverse grip bent over row': { canonicalIt: 'Rematore presa inversa con bilanciere', aliases: ['rematore inverso'] },
  'barbell reverse grip decline bench press': { canonicalIt: 'Panca declinata presa inversa con bilanciere', aliases: ['decline press inversa'] },
  'barbell reverse grip incline bench press': { canonicalIt: 'Panca inclinata presa inversa con bilanciere', aliases: ['incline press inversa'] },
  'barbell reverse grip skullcrusher': { canonicalIt: 'Skullcrusher presa inversa con bilanciere', aliases: ['skullcrusher inverso'] },
  'barbell reverse lunge': { canonicalIt: 'Affondi inversi con bilanciere', aliases: ['reverse lunge bilanciere'] },
  'barbell reverse preacher curl': { canonicalIt: 'Curl inverso su panca Scott con bilanciere', aliases: ['reverse preacher curl'] },
  'barbell reverse wrist curl': { canonicalIt: 'Reverse wrist curl con bilanciere', aliases: ['reverse curl polsi bilanciere'] },
  'barbell romanian deadlift': { canonicalIt: 'Romanian deadlift con bilanciere', aliases: ['rdl bilanciere', 'stiff rumeno'] },
  'barbell seated calf raise': { canonicalIt: 'Sollevamenti polpacci seduto con bilanciere', aliases: ['calf raise seduto bilanciere'] },
  'barbell seated close-grip concentration curl': { canonicalIt: 'Curl concentrazione seduto presa stretta con bilanciere', aliases: ['concentration curl bilanciere'] },
  'barbell seated good morning': { canonicalIt: 'Good morning seduto con bilanciere', aliases: ['good morning seduto'] },
  'barbell seated overhead triceps extension': { canonicalIt: 'Extension tricipiti seduto sopra testa con bilanciere', aliases: ['overhead triceps extension bilanciere'] },
  'barbell seated twist': { canonicalIt: 'Twist seduto con bilanciere', aliases: ['rotazione busto seduto bilanciere'] },
  'barbell shoulder press': { canonicalIt: 'Shoulder press con bilanciere', aliases: ['spalle bilanciere', 'military press'] },
  'barbell shrug': { canonicalIt: 'Shrug con bilanciere', aliases: ['shrug bilanciere'] },
  'barbell side bend': { canonicalIt: 'Flessioni laterali con bilanciere', aliases: ['side bend bilanciere'] },
  'barbell side split squat': { canonicalIt: 'Split squat laterale con bilanciere', aliases: ['split squat laterale'] },
  'barbell single leg deadlift': { canonicalIt: 'Stacco monogamba con bilanciere', aliases: ['single leg deadlift bilanciere'] },
  'barbell single leg split squat': { canonicalIt: 'Bulgarian split squat con bilanciere', aliases: ['split squat bulgaro bilanciere'] },
  'barbell sissy squat': { canonicalIt: 'Sissy squat con bilanciere', aliases: ['sissy squat'] },
  'barbell skullcrusher': { canonicalIt: 'Skullcrusher con bilanciere', aliases: ['skullcrusher bb'] },
  'barbell squat': { canonicalIt: 'Squat con bilanciere', aliases: ['squat bilanciere'] },
  'barbell standing ab rollout': { canonicalIt: 'Ab rollout in piedi con bilanciere', aliases: ['ab rollout bilanciere'] },
  'barbell standing back wrist curl': { canonicalIt: 'Wrist curl posteriore in piedi con bilanciere', aliases: ['wrist curl posteriore'] },
  'barbell standing bradford press': { canonicalIt: 'Bradford press in piedi con bilanciere', aliases: ['bradford press'] },
  'barbell standing calf raise': { canonicalIt: 'Sollevamenti polpacci in piedi con bilanciere', aliases: ['calf raise in piedi bilanciere'] },
  'barbell standing close grip curl': { canonicalIt: 'Curl presa stretta in piedi con bilanciere', aliases: ['curl stretto bilanciere'] },
  'barbell standing front raise': { canonicalIt: 'Alzate frontali in piedi con bilanciere', aliases: ['front raise bilanciere'] },
  'barbell standing leg calf raise': { canonicalIt: 'Calf raise gamba singola in piedi con bilanciere', aliases: ['single leg calf raise bilanciere'] },
  'barbell standing overhead triceps extension': { canonicalIt: 'Extension tricipiti sopra testa in piedi con bilanciere', aliases: ['overhead triceps ext bilanciere'] },
  'barbell standing reverse grip curl': { canonicalIt: 'Curl inverso in piedi con bilanciere', aliases: ['reverse curl in piedi'] },
  'barbell standing rockers': { canonicalIt: 'Rockers in piedi con bilanciere', aliases: ['barbell rockers'] },
  'barbell standing twisting curl': { canonicalIt: 'Curl rotante in piedi con bilanciere', aliases: ['twisting curl bilanciere'] },
  'barbell standing wide grip biceps curl': { canonicalIt: 'Curl bicipiti presa larga in piedi con bilanciere', aliases: ['curl largo bilanciere'] },
  'barbell standing wrist curl': { canonicalIt: 'Wrist curl in piedi con bilanciere', aliases: ['wrist curl bilanciere'] },
  'barbell sumo deadlift': { canonicalIt: 'Sumo deadlift con bilanciere', aliases: ['sumo deadlift'] },
  'barbell thruster': { canonicalIt: 'Thruster con bilanciere', aliases: ['thruster'] },
  'barbell upright row': { canonicalIt: 'Upright row con bilanciere', aliases: ['upright row bilanciere'] },
  'barbell wide bench press': { canonicalIt: 'Panca larga con bilanciere', aliases: ['panca larga', 'wide bench press'] },
  'barbell wide-grip upright row': { canonicalIt: 'Upright row presa larga con bilanciere', aliases: ['upright row largo'] },
  'barbell wrist curl': { canonicalIt: 'Wrist curl con bilanciere', aliases: ['curl polsi bilanciere'] },
  'battling ropes': { canonicalIt: 'Battle ropes', aliases: ['funi', 'corde'] },
  'bench dip (knees bent)': { canonicalIt: 'Dip panca ginocchia piegate', aliases: ['bench dip'] },
  'bench dip on floor': { canonicalIt: 'Dip a terra', aliases: ['floor dip'] },
  'bench pull-ups': { canonicalIt: 'Pull-up su panca bassa', aliases: ['pull up panca'] },
  'bent knee lying twist': { canonicalIt: 'Twist disteso ginocchia piegate', aliases: ['twist ginocchia piegate'] },
  'bent over dumbbell row': { canonicalIt: 'Rematore con manubrio', aliases: ['rematore manubrio', 'one arm dumbbell row'] },
  'bent over one-arm long bar row': { canonicalIt: 'Rematore monobraccio barra lunga', aliases: ['t-bar row monobraccio'] },
  'bent over two-arm long bar row': { canonicalIt: 'Rematore due braccia barra lunga', aliases: ['t-bar row'] },
  'bicep curl (barbell)': { canonicalIt: 'Curl bicipiti con bilanciere', aliases: ['curl bilanciere'] },
  'bicep curl (dumbbell)': { canonicalIt: 'Curl bicipiti con manubrio', aliases: ['curl manubrio'] },
  'body-up': { canonicalIt: 'Body-up', aliases: ['body up'] },
  'bodyweight drop jump squat': { canonicalIt: 'Drop jump squat a corpo libero', aliases: ['drop squat'] },
  'bodyweight incline side plank': { canonicalIt: 'Side plank inclinato a corpo libero', aliases: ['side plank inclinato'] },
  'bodyweight kneeling triceps extension': { canonicalIt: 'Extension tricipiti in ginocchio a corpo libero', aliases: ['triceps extension ginocchio'] },
  'bodyweight lunges': { canonicalIt: 'Affondi a corpo libero', aliases: ['affondi', 'lunges'] },
  'bodyweight side plank': { canonicalIt: 'Side plank a corpo libero', aliases: ['plank laterale'] },
  'bodyweight squat': { canonicalIt: 'Squat a corpo libero', aliases: ['squat', 'squat senza pesi'] },
  'bodyweight standing calf raise': { canonicalIt: 'Sollevamenti polpacci in piedi a corpo libero', aliases: ['calf raise corpo libero'] },
  'bosu ball curl-up': { canonicalIt: 'Curl-up su BOSU', aliases: ['bosu curl up'] },
  'bottoms-up': { canonicalIt: 'Bottoms-up', aliases: ['bottoms up'] },
  'box jump': { canonicalIt: 'Box jump', aliases: ['salto sul box'] },
  'box squat': { canonicalIt: 'Box squat', aliases: ['squat sul box'] },
  'bridge - mountain climber (cross body)': { canonicalIt: 'Mountain climber cross body da ponte', aliases: ['mountain climber cross'] },
  'butterfly': { canonicalIt: 'Farfalla', aliases: ['pec deck', 'butterfly macchina'] },
  'cable alternate shoulder press': { canonicalIt: 'Shoulder press alternato al cavo', aliases: ['shoulder press cavo alternato'] },
  'cable alternate triceps extension': { canonicalIt: 'Extension tricipiti alternato al cavo', aliases: ['triceps extension cavo alternato'] },
  'cable alternating cross-body hammer curl': { canonicalIt: 'Hammer curl cross-body alternato al cavo', aliases: ['hammer curl cavo cross'] },
  'cable bar lateral pulldown': { canonicalIt: 'Pulldown laterale al cavo con barra', aliases: ['lat pulldown cavo'] },
  'cable bench press': { canonicalIt: 'Panca piana al cavo', aliases: ['bench press cavo'] },
  'cable biceps curl': { canonicalIt: 'Curl bicipiti al cavo', aliases: ['curl cavo'] },
  'cable chest press': { canonicalIt: 'Chest press al cavo', aliases: ['chest press cavo'] },
  'cable close grip curl': { canonicalIt: 'Curl presa stretta al cavo', aliases: ['curl stretto cavo'] },
  'cable crossover': { canonicalIt: 'Croci ai cavi', aliases: ['crossover', 'cable fly', 'croci cavi'] },
  'cable curl': { canonicalIt: 'Curl al cavo', aliases: ['curl cavo'] },
  'cable deadlift': { canonicalIt: 'Stacco da terra al cavo', aliases: ['deadlift cavo'] },
  'cable decline fly': { canonicalIt: 'Croci declinate al cavo', aliases: ['decline fly cavo'] },
  'cable decline one arm press': { canonicalIt: 'Press declinato monobraccio al cavo', aliases: ['decline press cavo'] },
  'cable decline press': { canonicalIt: 'Panca declinata al cavo', aliases: ['decline press cavo'] },
  'cable fly': { canonicalIt: 'Croci al cavo', aliases: ['cable fly', 'croci cavi'] },
  'cable front raise': { canonicalIt: 'Alzate frontali al cavo', aliases: ['front raise cavo'] },
  'cable hip adduction': { canonicalIt: 'Adduzione fianchi al cavo', aliases: ['hip adduction cavo'] },
  'cable incline fly': { canonicalIt: 'Croci inclinate al cavo', aliases: ['incline fly cavo'] },
  'cable incline pushdown': { canonicalIt: 'Pushdown inclinato al cavo', aliases: ['incline pushdown cavo'] },
  'cable incline triceps extension': { canonicalIt: 'Extension tricipiti inclinato al cavo', aliases: ['incline triceps extension cavo'] },
  'cable iron cross': { canonicalIt: 'Iron cross al cavo', aliases: ['croce di ferro cavo'] },
  'cable judo flip': { canonicalIt: 'Judo flip al cavo', aliases: ['judo flip'] },
  'cable kneeling crunch': { canonicalIt: 'Crunch in ginocchio al cavo', aliases: ['kneeling crunch cavo'] },
  'cable kneeling triceps extension': { canonicalIt: 'Extension tricipiti in ginocchio al cavo', aliases: ['triceps extension ginocchio cavo'] },
  'cable lateral raise': { canonicalIt: 'Alzate laterali al cavo', aliases: ['lateral raise cavo'] },
  'cable lying biceps curl': { canonicalIt: 'Curl bicipiti disteso al cavo', aliases: ['lying curl cavo'] },
  'cable lying close-grip curl': { canonicalIt: 'Curl disteso presa stretta al cavo', aliases: ['lying curl stretto cavo'] },
  'cable lying fly': { canonicalIt: 'Croci distese al cavo', aliases: ['lying fly cavo'] },
  'cable lying triceps extension': { canonicalIt: 'Extension tricipiti disteso al cavo', aliases: ['lying triceps extension cavo'] },
  'cable one arm bent over lateral raise': { canonicalIt: 'Alzate laterali piegate monobraccio al cavo', aliases: ['bent over lateral raise cavo'] },
  'cable one arm curl': { canonicalIt: 'Curl monobraccio al cavo', aliases: ['curl monobraccio cavo'] },
  'cable one arm decline chest fly': { canonicalIt: 'Croce petto declinata monobraccio al cavo', aliases: ['decline fly monobraccio cavo'] },
  'cable one arm fly': { canonicalIt: 'Croce monobraccio al cavo', aliases: ['fly monobraccio cavo'] },
  'cable one arm incline fly': { canonicalIt: 'Croce inclinata monobraccio al cavo', aliases: ['incline fly monobraccio cavo'] },
  'cable one arm lateral raise': { canonicalIt: 'Alzata laterale monobraccio al cavo', aliases: ['lateral raise monobraccio cavo'] },
  'cable one arm preacher curl': { canonicalIt: 'Curl su panca Scott monobraccio al cavo', aliases: ['preacher curl cavo'] },
  'cable one arm pulldown': { canonicalIt: 'Pulldown monobraccio al cavo', aliases: ['pulldown monobraccio cavo'] },
  'cable one arm reverse fly': { canonicalIt: 'Reverse fly monobraccio al cavo', aliases: ['reverse fly monobraccio cavo'] },
  'cable one arm seated biceps curl': { canonicalIt: 'Curl bicipiti seduto monobraccio al cavo', aliases: ['curl seduto monobraccio cavo'] },
  'cable one arm seated overhead triceps extension': { canonicalIt: 'Extension tricipiti seduto monobraccio sopra testa al cavo', aliases: ['overhead triceps ext monobraccio cavo'] },
  'cable one arm tricep pushdown': { canonicalIt: 'Pushdown tricipiti monobraccio al cavo', aliases: ['pushdown monobraccio cavo'] },
  'cable overhead curl': { canonicalIt: 'Curl sopra testa al cavo', aliases: ['overhead curl cavo'] },
  'cable overhead triceps extension': { canonicalIt: 'Extension tricipiti sopra testa al cavo', aliases: ['overhead triceps extension cavo'] },
  'cable preacher curl': { canonicalIt: 'Curl su panca Scott al cavo', aliases: ['preacher curl cavo'] },
  'cable pullover': { canonicalIt: 'Pullover al cavo', aliases: ['pullover cavo'] },
  'cable pushdown': { canonicalIt: 'Pushdown al cavo', aliases: ['pushdown cavo'] },
  'cable rear delt fly': { canonicalIt: 'Reverse fly al cavo', aliases: ['rear delt fly cavo'] },
  'cable reverse crunch': { canonicalIt: 'Reverse crunch al cavo', aliases: ['reverse crunch cavo'] },
  'cable reverse curl': { canonicalIt: 'Curl inverso al cavo', aliases: ['reverse curl cavo'] },
  'cable reverse fly': { canonicalIt: 'Reverse fly al cavo', aliases: ['reverse fly cavo'] },
  'cable reverse grip triceps pushdown': { canonicalIt: 'Pushdown tricipiti presa inversa al cavo', aliases: ['pushdown inverso cavo'] },
  'cable rope hammer curl': { canonicalIt: 'Hammer curl con fune al cavo', aliases: ['rope hammer curl'] },
  'cable rope incline triceps extension': { canonicalIt: 'Extension tricipiti inclinato con fune al cavo', aliases: ['incline triceps extension fune'] },
  'cable rope overhead triceps extension': { canonicalIt: 'Extension tricipiti sopra testa con fune al cavo', aliases: ['overhead triceps extension fune'] },
  'cable rope seated row': { canonicalIt: 'Rematore seduto con fune al cavo', aliases: ['seated row fune'] },
  'cable russian twists': { canonicalIt: 'Russian twist al cavo', aliases: ['russian twist cavo'] },
  'cable seated chest press': { canonicalIt: 'Chest press seduto al cavo', aliases: ['seated chest press cavo'] },
  'cable seated crunch': { canonicalIt: 'Crunch seduto al cavo', aliases: ['seated crunch cavo'] },
  'cable seated lateral raise': { canonicalIt: 'Alzate laterali seduto al cavo', aliases: ['seated lateral raise cavo'] },
  'cable seated one arm alternate curl': { canonicalIt: 'Curl alternato seduto monobraccio al cavo', aliases: ['seated curl alternato cavo'] },
  'cable seated rear lateral raise': { canonicalIt: 'Alzate laterali posteriori seduto al cavo', aliases: ['seated rear lateral raise cavo'] },
  'cable seated row': { canonicalIt: 'Rematore seduto al cavo', aliases: ['seated row cavo'] },
  'cable seated shoulder internal rotation': { canonicalIt: 'Rotazione interna spalla seduto al cavo', aliases: ['internal rotation cavo'] },
  'cable shoulder press': { canonicalIt: 'Shoulder press al cavo', aliases: ['shoulder press cavo'] },
  'cable shrug': { canonicalIt: 'Shrug al cavo', aliases: ['shrug cavo'] },
  'cable side bend': { canonicalIt: 'Flessione laterale al cavo', aliases: ['side bend cavo'] },
  'cable squat': { canonicalIt: 'Squat al cavo', aliases: ['squat cavo'] },
  'cable squat row': { canonicalIt: 'Squat row al cavo', aliases: ['squat row cavo'] },
  'cable standing back wrist curl': { canonicalIt: 'Wrist curl posteriore in piedi al cavo', aliases: ['back wrist curl cavo'] },
  'cable standing calf raise': { canonicalIt: 'Sollevamenti polpacci in piedi al cavo', aliases: ['calf raise cavo'] },
  'cable standing crunch': { canonicalIt: 'Crunch in piedi al cavo', aliases: ['standing crunch cavo'] },
  'cable standing fly': { canonicalIt: 'Croci in piedi al cavo', aliases: ['standing fly cavo'] },
  'cable standing inner curl': { canonicalIt: 'Curl interno in piedi al cavo', aliases: ['inner curl cavo'] },
  'cable standing one arm triceps extension': { canonicalIt: 'Extension tricipiti monobraccio in piedi al cavo', aliases: ['standing triceps extension cavo'] },
  'cable standing pulldown': { canonicalIt: 'Pulldown in piedi al cavo', aliases: ['standing pulldown cavo'] },
  'cable standing reverse fly': { canonicalIt: 'Reverse fly in piedi al cavo', aliases: ['standing reverse fly cavo'] },
  'cable standing row': { canonicalIt: 'Rematore in piedi al cavo', aliases: ['standing row cavo'] },
  'cable standing shoulder external rotation': { canonicalIt: 'Rotazione esterna spalla in piedi al cavo', aliases: ['external rotation cavo'] },
  'cable standing twist': { canonicalIt: 'Twist in piedi al cavo', aliases: ['twist cavo'] },
  'cable standing upright row': { canonicalIt: 'Upright row in piedi al cavo', aliases: ['upright row cavo'] },
  'cable standing wrist curl': { canonicalIt: 'Wrist curl in piedi al cavo', aliases: ['wrist curl cavo'] },
  'cable straight arm pulldown': { canonicalIt: 'Pulldown braccia tese al cavo', aliases: ['straight arm pulldown cavo'] },
  'cable straddle over': { canonicalIt: 'Straddle over al cavo', aliases: ['straddle over'] },
  'cable triceps pushdown': { canonicalIt: 'Pushdown tricipiti al cavo', aliases: ['pushdown tricipiti', 'triceps pushdown'] },
  'cable twist': { canonicalIt: 'Twist al cavo', aliases: ['twist cavo'] },
  'cable two arm curl on incline bench': { canonicalIt: 'Curl due braccia su panca inclinata al cavo', aliases: ['incline curl cavo'] },
  'cable two arm tricep kickback': { canonicalIt: 'Kickback tricipiti due braccia al cavo', aliases: ['tricep kickback cavo'] },
  'cable upright row': { canonicalIt: 'Upright row al cavo', aliases: ['upright row cavo'] },
  'cable wrist curl': { canonicalIt: 'Wrist curl al cavo', aliases: ['wrist curl cavo'] },
  'calf press on leg press': { canonicalIt: 'Pressa polpacci su leg press', aliases: ['calf press leg press'] },
  'calf raise on a step': { canonicalIt: 'Sollevamenti polpacci su gradino', aliases: ['calf raise gradino'] },
  'calf raises': { canonicalIt: 'Sollevamenti polpacci', aliases: ['calf raise'] },
  'calf stretch elbows against wall': { canonicalIt: 'Stretch polpacci gomiti contro muro', aliases: ['calf stretch'] },
  'captains chair straight leg raise': { canonicalIt: 'Sollevamento gambe tese su captains chair', aliases: ['leg raise captains chair'] },
  'cardio': { canonicalIt: 'Cardio', aliases: ['cardio'] },
  'chair leg extended stretch': { canonicalIt: 'Stretch gamba estesa sulla sedia', aliases: ['leg stretch sedia'] },
  'chest and front of shoulder stretch': { canonicalIt: 'Stretch petto e parte anteriore spalla', aliases: ['chest stretch'] },
  'chest dip': { canonicalIt: 'Dip petto', aliases: ['dip petto', 'dip'] },
  'chest press': { canonicalIt: 'Chest press', aliases: ['chest press macchina', 'pressa petto'] },
  'chest stretch on stability ball': { canonicalIt: 'Stretch petto su stability ball', aliases: ['chest stretch fitball'] },
  'chest tap push-up': { canonicalIt: 'Push-up con tocchi al petto', aliases: ['chest tap push up'] },
  'chin-up': { canonicalIt: 'Chin-up', aliases: ['chin up', 'trazione presa stretta'] },
  'clean and jerk': { canonicalIt: 'Clean and jerk', aliases: ['clean jerk'] },
  'clock push-up': { canonicalIt: 'Clock push-up', aliases: ['push up orologio'] },
  'close-grip push-up': { canonicalIt: 'Push-up presa stretta', aliases: ['push up stretto'] },
  'cocoon': { canonicalIt: 'Cocoon', aliases: ['cocoon abs'] },
  'crab walk toe touch': { canonicalIt: 'Crab walk toe touch', aliases: ['crab walk'] },
  'cross body crunch': { canonicalIt: 'Crunch cross-body', aliases: ['crunch obliquo'] },
  'crunch (legs on bench)': { canonicalIt: 'Crunch con gambe sulla panca', aliases: ['crunch gambe panca'] },
  'crunch floor': { canonicalIt: 'Crunch a terra', aliases: ['crunch'] },
  'crunch': { canonicalIt: 'Crunch', aliases: ['crunch addominali'] },
  'curl-up': { canonicalIt: 'Curl-up', aliases: ['curl up'] },
  'dead bug': { canonicalIt: 'Dead bug', aliases: ['deadbug'] },
  'decline bench press': { canonicalIt: 'Panca declinata', aliases: ['decline press'] },
  'decline close-grip bench to skull crusher': { canonicalIt: 'Panca declinata stretta a skull crusher', aliases: ['decline skull crusher'] },
  'decline crunch': { canonicalIt: 'Crunch declinato', aliases: ['crunch declino'] },
  'decline dumbbell bench press': { canonicalIt: 'Panca declinata con manubri', aliases: ['decline dumbbell press'] },
  'decline dumbbell fly': { canonicalIt: 'Croci declinate con manubri', aliases: ['decline fly manubri'] },
  'decline dumbbell triceps extension': { canonicalIt: 'Extension tricipiti declinata con manubri', aliases: ['decline triceps ext manubri'] },
  'decline ez bar skullcrusher': { canonicalIt: 'Skullcrusher con EZ bar declinato', aliases: ['decline ez skullcrusher'] },
  'decline oblique crunch': { canonicalIt: 'Crunch obliquo declinato', aliases: ['decline oblique crunch'] },
  'decline push-up': { canonicalIt: 'Push-up declinato', aliases: ['push up declinato'] },
  'decline reverse crunch': { canonicalIt: 'Reverse crunch declinato', aliases: ['reverse crunch declinato'] },
  'decline sit-up': { canonicalIt: 'Sit-up declinato', aliases: ['sit up declinato'] },
  'depth jump': { canonicalIt: 'Depth jump', aliases: ['salto da profondità'] },
  'dip': { canonicalIt: 'Dip', aliases: ['dip tricipiti', 'dip'] },
  'dips between benches': { canonicalIt: 'Dip tra due panche', aliases: ['dip tra panche'] },
  'donkey calf raise': { canonicalIt: 'Donkey calf raise', aliases: ['calf raise asino'] },
  'dumbbell alternate biceps curl': { canonicalIt: 'Curl bicipiti alternato con manubri', aliases: ['curl alternato manubri'] },
  'dumbbell alternate hammer preacher curl': { canonicalIt: 'Hammer curl alternato su panca Scott con manubri', aliases: ['hammer curl scott alternato'] },
  'dumbbell alternate preacher curl': { canonicalIt: 'Curl alternato su panca Scott con manubri', aliases: ['preacher curl alternato manubri'] },
  'dumbbell alternating bicep curl': { canonicalIt: 'Curl bicipite alternato con manubri', aliases: ['curl alternato manubrio'] },
  'dumbbell alternating shoulder press': { canonicalIt: 'Shoulder press alternato con manubri', aliases: ['shoulder press alternato manubri'] },
  'dumbbell arnold press': { canonicalIt: 'Arnold press con manubri', aliases: ['arnold press'] },
  'dumbbell arnold press ii': { canonicalIt: 'Arnold press II con manubri', aliases: ['arnold press 2'] },
  'dumbbell bench press': { canonicalIt: 'Panca piana con manubri', aliases: ['panca manubri', 'dumbbell press', 'panca piana db'] },
  'dumbbell bent arm pullover': { canonicalIt: 'Pullover con braccia piegate con manubri', aliases: ['pullover manubri'] },
  'dumbbell bent over row': { canonicalIt: 'Rematore con manubri', aliases: ['rematore manubri'] },
  'dumbbell bicep curl': { canonicalIt: 'Curl bicipite con manubrio', aliases: ['curl manubrio', 'curl bicipiti'] },
  'dumbbell clean': { canonicalIt: 'Clean con manubri', aliases: ['dumbbell clean'] },
  'dumbbell close-grip bench press': { canonicalIt: 'Panca stretta con manubri', aliases: ['close grip bench manubri'] },
  'dumbbell concentration curl': { canonicalIt: 'Curl concentrazione con manubrio', aliases: ['concentration curl'] },
  'dumbbell cross body hammer curl': { canonicalIt: 'Hammer curl cross-body con manubri', aliases: ['cross body hammer curl'] },
  'dumbbell cuban press': { canonicalIt: 'Cuban press con manubri', aliases: ['cuban press'] },
  'dumbbell deadlift': { canonicalIt: 'Stacco da terra con manubri', aliases: ['deadlift manubri'] },
  'dumbbell decline bench press': { canonicalIt: 'Panca declinata con manubri', aliases: ['decline bench manubri'] },
  'dumbbell decline fly': { canonicalIt: 'Croci declinate con manubri', aliases: ['decline fly manubri'] },
  'dumbbell decline one arm hammer press': { canonicalIt: 'Hammer press declinato monobraccio con manubrio', aliases: ['decline hammer press'] },
  'dumbbell decline shrug': { canonicalIt: 'Shrug declinato con manubri', aliases: ['decline shrug'] },
  'dumbbell decline triceps extension': { canonicalIt: 'Extension tricipiti declinata con manubri', aliases: ['decline triceps ext manubri'] },
  'dumbbell farmers walk': { canonicalIt: 'Farmer walk con manubri', aliases: ['farmer walk'] },
  'dumbbell fly': { canonicalIt: 'Croci con manubri', aliases: ['croci manubri', 'dumbbell fly'] },
  'dumbbell front raise': { canonicalIt: 'Alzate frontali con manubri', aliases: ['front raise manubri'] },
  'dumbbell full can lateral raise': { canonicalIt: 'Full can lateral raise con manubri', aliases: ['full can lateral raise'] },
  'dumbbell goblet squat': { canonicalIt: 'Goblet squat con manubrio', aliases: ['goblet squat', 'squat goblet'] },
  'dumbbell hammer curl': { canonicalIt: 'Hammer curl con manubri', aliases: ['hammer curl manubri'] },
  'dumbbell hammer curls (with arm blaster)': { canonicalIt: 'Hammer curl con arm blaster', aliases: ['hammer curl arm blaster'] },
  'dumbbell high curls': { canonicalIt: 'High curl con manubri', aliases: ['high curl'] },
  'dumbbell incline alternate press': { canonicalIt: 'Panca inclinata alternata con manubri', aliases: ['incline press alternato manubri'] },
  'dumbbell incline bench press': { canonicalIt: 'Panca inclinata con manubri', aliases: ['incline dumbbell press', 'panca inclinata manubri'] },
  'dumbbell incline biceps curl': { canonicalIt: 'Curl bicipiti su panca inclinata con manubri', aliases: ['incline curl manubri'] },
  'dumbbell incline curl': { canonicalIt: 'Curl su panca inclinata con manubri', aliases: ['incline curl'] },
  'dumbbell incline fly': { canonicalIt: 'Croci inclinate con manubri', aliases: ['incline fly manubri'] },
  'dumbbell incline hammer curl': { canonicalIt: 'Hammer curl su panca inclinata con manubri', aliases: ['incline hammer curl'] },
  'dumbbell incline hammer press': { canonicalIt: 'Hammer press su panca inclinata con manubri', aliases: ['incline hammer press'] },
  'dumbbell incline inner biceps curl': { canonicalIt: 'Curl bicipiti interno su panca inclinata con manubri', aliases: ['incline inner curl'] },
  'dumbbell incline one arm hammer press': { canonicalIt: 'Hammer press inclinato monobraccio con manubrio', aliases: ['incline hammer press monobraccio'] },
  'dumbbell incline one arm lateral raise': { canonicalIt: 'Alzata laterale inclinata monobraccio con manubrio', aliases: ['incline lateral raise monobraccio'] },
  'dumbbell incline shoulder raise': { canonicalIt: 'Shoulder raise su panca inclinata con manubri', aliases: ['incline shoulder raise'] },
  'dumbbell incline shrug': { canonicalIt: 'Shrug su panca inclinata con manubri', aliases: ['incline shrug'] },
  'dumbbell incline t-raise': { canonicalIt: 'T-raise su panca inclinata con manubri', aliases: ['incline t raise'] },
  'dumbbell incline triceps extension': { canonicalIt: 'Extension tricipiti su panca inclinata con manubri', aliases: ['incline triceps ext manubri'] },
  'dumbbell incline two arm extension': { canonicalIt: 'Extension due braccia su panca inclinata con manubri', aliases: ['incline two arm extension'] },
  'dumbbell incline y-raise': { canonicalIt: 'Y-raise su panca inclinata con manubri', aliases: ['incline y raise'] },
  'dumbbell iron cross': { canonicalIt: 'Iron cross con manubri', aliases: ['iron cross manubri'] },
  'dumbbell kickback': { canonicalIt: 'Kickback tricipiti con manubrio', aliases: ['tricep kickback', 'kickback'] },
  'dumbbell lateral raise': { canonicalIt: 'Alzate laterali con manubri', aliases: ['lateral raise manubri', 'alzate laterali'] },
  'dumbbell lateral to front raise': { canonicalIt: 'Alzate laterali-frontali con manubri', aliases: ['lateral to front raise'] },
  'dumbbell leaning alternate lateral raise': { canonicalIt: 'Alzate laterali alternate in appoggio con manubri', aliases: ['leaning lateral raise'] },
  'dumbbell lying calf raise': { canonicalIt: 'Sollevamenti polpacci distesi con manubri', aliases: ['lying calf raise'] },
  'dumbbell lying elbow press': { canonicalIt: 'Elbow press disteso con manubri', aliases: ['lying elbow press'] },
  'dumbbell lying external shoulder rotation': { canonicalIt: 'Rotazione esterna spalla distesa con manubrio', aliases: ['external rotation manubrio'] },
  'dumbbell lying femoral': { canonicalIt: 'Curl femorali disteso con manubrio', aliases: ['lying leg curl manubrio'] },
  'dumbbell lying hammer curl': { canonicalIt: 'Hammer curl disteso con manubri', aliases: ['lying hammer curl'] },
  'dumbbell lying on floor rear delt raise': { canonicalIt: 'Alzate deltoidi posteriori distesi a terra con manubri', aliases: ['floor rear delt raise'] },
  'dumbbell lying one arm deltoid rear': { canonicalIt: 'Deltoidi posteriori monobraccio disteso con manubrio', aliases: ['lying rear delt'] },
  'dumbbell lying one arm press': { canonicalIt: 'Press monobraccio disteso con manubrio', aliases: ['lying one arm press'] },
  'dumbbell lying pullover': { canonicalIt: 'Pullover disteso con manubrio', aliases: ['dumbbell pullover'] },
  'dumbbell lying rear delt row': { canonicalIt: 'Rematore deltoidi posteriori disteso con manubri', aliases: ['lying rear delt row'] },
  'dumbbell lying single leg calf raise': { canonicalIt: 'Sollevamento polpacci monogamba disteso con manubrio', aliases: ['lying single leg calf raise'] },
  'dumbbell lying supination': { canonicalIt: 'Supinazione distesa con manubrio', aliases: ['dumbbell supination'] },
  'dumbbell lying triceps extension': { canonicalIt: 'Extension tricipiti disteso con manubri', aliases: ['skullcrusher manubri', 'french press manubri'] },
  'dumbbell one arm bench press': { canonicalIt: 'Panca piana monobraccio con manubrio', aliases: ['one arm bench press'] },
  'dumbbell one arm biceps curl': { canonicalIt: 'Curl bicipite monobraccio con manubrio', aliases: ['one arm curl manubrio'] },
  'dumbbell one arm chest fly on exercise ball': { canonicalIt: 'Croce petto monobraccio su fitball con manubrio', aliases: ['one arm fly fitball'] },
  'dumbbell one arm floor press': { canonicalIt: 'Floor press monobraccio con manubrio', aliases: ['one arm floor press'] },
  'dumbbell one arm front raise': { canonicalIt: 'Alzata frontale monobraccio con manubrio', aliases: ['one arm front raise'] },
  'dumbbell one arm hammer curl': { canonicalIt: 'Hammer curl monobraccio con manubrio', aliases: ['one arm hammer curl'] },
  'dumbbell one arm hammer preacher curl': { canonicalIt: 'Hammer curl su panca Scott monobraccio con manubrio', aliases: ['one arm hammer preacher curl'] },
  'dumbbell one arm incline chest press': { canonicalIt: 'Panca inclinata petto monobraccio con manubrio', aliases: ['one arm incline press'] },
  'dumbbell one arm kickback': { canonicalIt: 'Kickback monobraccio con manubrio', aliases: ['one arm kickback'] },
  'dumbbell one arm lateral raise': { canonicalIt: 'Alzata laterale monobraccio con manubrio', aliases: ['one arm lateral raise'] },
  'dumbbell one arm lateral raise with support': { canonicalIt: 'Alzata laterale monobraccio con supporto', aliases: ['supported lateral raise'] },
  'dumbbell one arm preacher curl': { canonicalIt: 'Curl su panca Scott monobraccio con manubrio', aliases: ['one arm preacher curl'] },
  'dumbbell one arm reverse spider curl': { canonicalIt: 'Reverse spider curl monobraccio con manubrio', aliases: ['one arm reverse spider curl'] },
  'dumbbell one arm reverse wrist curl': { canonicalIt: 'Reverse wrist curl monobraccio con manubrio', aliases: ['one arm reverse wrist curl'] },
  'dumbbell one arm seated biceps curl': { canonicalIt: 'Curl bicipite seduto monobraccio con manubrio', aliases: ['one arm seated curl'] },
  'dumbbell one arm seated curl': { canonicalIt: 'Curl seduto monobraccio con manubrio', aliases: ['one arm curl seduto'] },
  'dumbbell one arm seated hammer curl': { canonicalIt: 'Hammer curl seduto monobraccio con manubrio', aliases: ['one arm seated hammer curl'] },
  'dumbbell one arm seated overhead triceps extension': { canonicalIt: 'Extension tricipiti seduto monobraccio sopra testa con manubrio', aliases: ['one arm overhead triceps ext'] },
  'dumbbell one arm shoulder press': { canonicalIt: 'Shoulder press monobraccio con manubrio', aliases: ['one arm shoulder press'] },
  'dumbbell one arm snatch': { canonicalIt: 'Snatch monobraccio con manubrio', aliases: ['one arm dumbbell snatch'] },
  'dumbbell one arm upright row': { canonicalIt: 'Upright row monobraccio con manubrio', aliases: ['one arm upright row'] },
  'dumbbell one arm wrist curl': { canonicalIt: 'Wrist curl monobraccio con manubrio', aliases: ['one arm wrist curl'] },
  'dumbbell one arm zottman curl': { canonicalIt: 'Zottman curl monobraccio con manubrio', aliases: ['one arm zottman curl'] },
  'dumbbell one leg split squat': { canonicalIt: 'Bulgarian split squat monogamba con manubri', aliases: ['one leg split squat'] },
  'dumbbell overhead squat': { canonicalIt: 'Overhead squat con manubri', aliases: ['overhead squat manubri'] },
  'dumbbell palms-in shoulder press': { canonicalIt: 'Shoulder press palme inwards con manubri', aliases: ['palms in shoulder press'] },
  'dumbbell peck deck fly': { canonicalIt: 'Croci al pec deck con manubri', aliases: ['peck deck fly manubri'] },
  'dumbbell plank rotation': { canonicalIt: 'Rotazione plank con manubrio', aliases: ['plank rotation dumbbell'] },
  'dumbbell preacher curl': { canonicalIt: 'Curl su panca Scott con manubri', aliases: ['preacher curl manubri'] },
  'dumbbell press': { canonicalIt: 'Panca piana con manubri', aliases: ['dumbbell bench press'] },
  'dumbbell pullover': { canonicalIt: 'Pullover con manubrio', aliases: ['pullover manubrio'] },
  'dumbbell push press': { canonicalIt: 'Push press con manubri', aliases: ['dumbbell push press'] },
  'dumbbell push-up': { canonicalIt: 'Push-up con manubri', aliases: ['push up manubri'] },
  'dumbbell rear delt row': { canonicalIt: 'Rematore deltoidi posteriori con manubri', aliases: ['rear delt row manubri'] },
  'dumbbell rear fly': { canonicalIt: 'Reverse fly con manubri', aliases: ['rear fly manubri'] },
  'dumbbell reverse bench press': { canonicalIt: 'Panca inversa con manubri', aliases: ['reverse bench press manubri'] },
  'dumbbell reverse fly': { canonicalIt: 'Reverse fly con manubri', aliases: ['reverse fly manubri'] },
  'dumbbell reverse grip incline bench press': { canonicalIt: 'Panca inclinata presa inversa con manubri', aliases: ['reverse grip incline press'] },
  'dumbbell reverse lunge': { canonicalIt: 'Affondi inversi con manubri', aliases: ['reverse lunge manubri'] },
  'dumbbell reverse wrist curl': { canonicalIt: 'Reverse wrist curl con manubri', aliases: ['reverse wrist curl manubri'] },
  'dumbbell romanian deadlift': { canonicalIt: 'Romanian deadlift con manubri', aliases: ['rdl manubri', 'stiff rumeno manubri'] },
  'dumbbell rotation reverse fly': { canonicalIt: 'Reverse fly rotatorio con manubri', aliases: ['rotation reverse fly'] },
  'dumbbell scott press': { canonicalIt: 'Scott press con manubri', aliases: ['scott press'] },
  'dumbbell seated alternate bicep curl': { canonicalIt: 'Curl bicipite alternato seduto con manubri', aliases: ['seated curl alternato'] },
  'dumbbell seated alternate front raise': { canonicalIt: 'Alzate frontali alternate seduto con manubri', aliases: ['seated front raise alternato'] },
  'dumbbell seated alternate hammer curl': { canonicalIt: 'Hammer curl alternato seduto con manubri', aliases: ['seated hammer curl alternato'] },
  'dumbbell seated alternate lateral raise': { canonicalIt: 'Alzate laterali alternate seduto con manubri', aliases: ['seated lateral raise alternato'] },
  'dumbbell seated biceps curl': { canonicalIt: 'Curl bicipiti seduto con manubri', aliases: ['seated curl manubri'] },
  'dumbbell seated bent arm lateral raise': { canonicalIt: 'Alzate laterali braccia piegate seduto con manubri', aliases: ['seated bent arm lateral raise'] },
  'dumbbell seated bent over alternate kickback': { canonicalIt: 'Kickback alternato piegato seduto con manubri', aliases: ['seated kickback alternato'] },
  'dumbbell seated bent over kickback': { canonicalIt: 'Kickback piegato seduto con manubri', aliases: ['seated kickback'] },
  'dumbbell seated curl': { canonicalIt: 'Curl seduto con manubri', aliases: ['seated curl'] },
  'dumbbell seated front raise': { canonicalIt: 'Alzate frontali seduto con manubri', aliases: ['seated front raise'] },
  'dumbbell seated hammer curl': { canonicalIt: 'Hammer curl seduto con manubri', aliases: ['seated hammer curl'] },
  'dumbbell seated inner biceps curl': { canonicalIt: 'Curl bicipiti interno seduto con manubri', aliases: ['seated inner curl'] },
  'dumbbell seated lateral raise': { canonicalIt: 'Alzate laterali seduto con manubri', aliases: ['seated lateral raise'] },
  'dumbbell seated one arm biceps curl': { canonicalIt: 'Curl bicipite monobraccio seduto con manubrio', aliases: ['seated one arm curl'] },
  'dumbbell seated one arm kickback': { canonicalIt: 'Kickback monobraccio seduto con manubrio', aliases: ['seated one arm kickback'] },
  'dumbbell seated one arm lateral raise': { canonicalIt: 'Alzata laterale monobraccio seduto con manubrio', aliases: ['seated one arm lateral raise'] },
  'dumbbell seated one leg calf raise': { canonicalIt: 'Sollevamento polpacci monogamba seduto con manubrio', aliases: ['seated one leg calf raise'] },
  'dumbbell seated overhead triceps extension': { canonicalIt: 'Extension tricipiti seduto sopra testa con manubri', aliases: ['seated overhead triceps ext'] },
  'dumbbell seated palm up wrist curl': { canonicalIt: 'Wrist curl palma su seduto con manubri', aliases: ['seated wrist curl'] },
  'dumbbell seated preacher curl': { canonicalIt: 'Curl su panca Scott seduto con manubri', aliases: ['seated preacher curl'] },
  'dumbbell seated reverse grip biceps curl': { canonicalIt: 'Curl bicipiti presa inversa seduto con manubri', aliases: ['seated reverse curl'] },
  'dumbbell seated shoulder press': { canonicalIt: 'Shoulder press seduto con manubri', aliases: ['seated shoulder press manubri'] },
  'dumbbell seated triceps extension': { canonicalIt: 'Extension tricipiti seduto con manubri', aliases: ['seated triceps extension'] },
  'dumbbell shoulder press': { canonicalIt: 'Shoulder press con manubri', aliases: ['spalle manubri', 'military press manubri'] },
  'dumbbell shrug': { canonicalIt: 'Shrug con manubri', aliases: ['shrug manubri'] },
  'dumbbell side bend': { canonicalIt: 'Flessioni laterali con manubrio', aliases: ['side bend manubrio'] },
  'dumbbell side lunge': { canonicalIt: 'Affondo laterale con manubri', aliases: ['side lunge manubri'] },
  'dumbbell single leg deadlift': { canonicalIt: 'Stacco monogamba con manubri', aliases: ['single leg deadlift manubri'] },
  'dumbbell single leg split squat': { canonicalIt: 'Bulgarian split squat con manubri', aliases: ['split squat manubri'] },
  'dumbbell squat': { canonicalIt: 'Squat con manubri', aliases: ['squat manubri'] },
  'dumbbell standing biceps curl': { canonicalIt: 'Curl bicipiti in piedi con manubri', aliases: ['standing curl manubri'] },
  'dumbbell standing calf raise': { canonicalIt: 'Sollevamenti polpacci in piedi con manubri', aliases: ['standing calf raise manubri'] },
  'dumbbell standing front raise': { canonicalIt: 'Alzate frontali in piedi con manubri', aliases: ['standing front raise manubri'] },
  'dumbbell standing overhead triceps extension': { canonicalIt: 'Extension tricipiti sopra testa in piedi con manubri', aliases: ['standing overhead triceps ext'] },
  'dumbbell standing palms in curl': { canonicalIt: 'Curl palme inwards in piedi con manubri', aliases: ['standing palms in curl'] },
  'dumbbell standing preacher curl': { canonicalIt: 'Curl su panca Scott in piedi con manubri', aliases: ['standing preacher curl'] },
  'dumbbell standing reverse curl': { canonicalIt: 'Curl inverso in piedi con manubri', aliases: ['standing reverse curl'] },
  'dumbbell standing triceps extension': { canonicalIt: 'Extension tricipiti in piedi con manubri', aliases: ['standing triceps extension'] },
  'dumbbell standing wrist curl': { canonicalIt: 'Wrist curl in piedi con manubri', aliases: ['standing wrist curl manubri'] },
  'dumbbell step-up': { canonicalIt: 'Step-up con manubri', aliases: ['step up manubri'] },
  'dumbbell step-up split squat': { canonicalIt: 'Step-up split squat con manubri', aliases: ['step up split squat'] },
  'dumbbell stiff leg deadlift': { canonicalIt: 'Stiff leg deadlift con manubri', aliases: ['stiff leg deadlift manubri'] },
  'dumbbell straight arm pulldown': { canonicalIt: 'Pulldown braccia tese con manubrio', aliases: ['straight arm pulldown manubrio'] },
  'dumbbell sumo deadlift': { canonicalIt: 'Sumo deadlift con manubri', aliases: ['sumo deadlift manubri'] },
  'dumbbell tate press': { canonicalIt: 'Tate press con manubri', aliases: ['tate press'] },
  'dumbbell thruster': { canonicalIt: 'Thruster con manubri', aliases: ['thruster manubri'] },
  'dumbbell upright row': { canonicalIt: 'Upright row con manubri', aliases: ['upright row manubri'] },
  'dumbbell wrist curl': { canonicalIt: 'Wrist curl con manubri', aliases: ['wrist curl manubri'] },
  'dumbbell zottman curl': { canonicalIt: 'Zottman curl con manubri', aliases: ['zottman curl'] },
  'elbow lift - reverse push-up': { canonicalIt: 'Elbow lift reverse push-up', aliases: ['elbow lift'] },
  'elliptical trainer': { canonicalIt: 'Ellittica', aliases: ['elliptical'] },
  'exercise ball alternating arm swing': { canonicalIt: 'Arm swing alternato su fitball', aliases: ['arm swing fitball'] },
  'exercise ball back extension': { canonicalIt: 'Iperextensione lombare su fitball', aliases: ['back extension fitball'] },
  'exercise ball crunch': { canonicalIt: 'Crunch su fitball', aliases: ['crunch fitball'] },
  'exercise ball dip': { canonicalIt: 'Dip su fitball', aliases: ['dip fitball'] },
  'exercise ball hip flexor stretch': { canonicalIt: 'Stretch flessori dell\'anca su fitball', aliases: ['hip flexor stretch fitball'] },
  'exercise ball lat stretch': { canonicalIt: 'Stretch dorsali su fitball', aliases: ['lat stretch fitball'] },
  'exercise ball lower back stretch': { canonicalIt: 'Stretch lombare su fitball', aliases: ['lower back stretch fitball'] },
  'exercise ball pelvic isolation': { canonicalIt: 'Isolamento pelvico su fitball', aliases: ['pelvic isolation fitball'] },
  'exercise ball pike push up': { canonicalIt: 'Pike push-up su fitball', aliases: ['pike push up fitball'] },
  'exercise ball pull-in': { canonicalIt: 'Pull-in su fitball', aliases: ['pull in fitball'] },
  'exercise ball push-up': { canonicalIt: 'Push-up su fitball', aliases: ['push up fitball'] },
  'exercise ball seated hamstring stretch': { canonicalIt: 'Stretch ischiocrurali seduto su fitball', aliases: ['hamstring stretch fitball'] },
  'exercise ball supinated back extension': { canonicalIt: 'Iperextensione lombare supina su fitball', aliases: ['back extension supina fitball'] },
  'ez barbell curl': { canonicalIt: 'Curl con barra EZ', aliases: ['ez bar curl', 'curl ez'] },
  'ez barbell spider curl': { canonicalIt: 'Spider curl con barra EZ', aliases: ['spider curl ez'] },
  'ez-bar close-grip bench press': { canonicalIt: 'Panca stretta con EZ bar', aliases: ['close grip bench ez'] },
  'ez-bar curl': { canonicalIt: 'Curl con EZ bar', aliases: ['curl ez bar'] },
  'ez-bar decline close-grip bench press': { canonicalIt: 'Panca declinata stretta con EZ bar', aliases: ['decline close grip ez'] },
  'ez-bar reverse grip curl': { canonicalIt: 'Curl presa inversa con EZ bar', aliases: ['reverse curl ez'] },
  'ez-bar seated close-grip concentration curl': { canonicalIt: 'Curl concentrazione seduto stretto con EZ bar', aliases: ['seated concentration curl ez'] },
  'ez-bar seated curls': { canonicalIt: 'Curl seduto con EZ bar', aliases: ['seated curl ez'] },
  'ez-bar skullcrusher': { canonicalIt: 'Skullcrusher con EZ bar', aliases: ['skullcrusher ez'] },
  'face pull': { canonicalIt: 'Face pull', aliases: ['face pull cavo'] },
  'farmer walk': { canonicalIt: 'Farmer walk', aliases: ['farmer carry'] },
  'flat bench leg pull-in': { canonicalIt: 'Leg pull-in su panca piana', aliases: ['leg pull in'] },
  'flat bench lying leg raise': { canonicalIt: 'Sollevamento gambe disteso su panca piana', aliases: ['lying leg raise'] },
  'flexion leg sit up': { canonicalIt: 'Sit-up con flessione gambe', aliases: ['leg sit up'] },
  'floor crunch': { canonicalIt: 'Crunch a terra', aliases: ['floor crunch'] },
  'floor dip': { canonicalIt: 'Dip a terra', aliases: ['floor dip'] },
  'flutter kicks': { canonicalIt: 'Flutter kicks', aliases: ['colpi di gambe'] },
  'front lever': { canonicalIt: 'Front lever', aliases: ['leva anteriore'] },
  'frog crunch': { canonicalIt: 'Crunch rana', aliases: ['frog crunch'] },
  'frog planche': { canonicalIt: 'Frog planche', aliases: ['planche rana'] },
  'good morning': { canonicalIt: 'Good morning', aliases: ['good morning'] },
  'gorilla chin crunch': { canonicalIt: 'Gorilla chin crunch', aliases: ['gorilla chin'] },
  'hack squat': { canonicalIt: 'Hack squat', aliases: ['hack squat'] },
  'hammer curl': { canonicalIt: 'Hammer curl', aliases: ['hammer curl'] },
  'handstand push-up': { canonicalIt: 'Handstand push-up', aliases: ['piegamento in verticale'] },
  'hanging leg raise': { canonicalIt: 'Sollevamento gambe in sospensione', aliases: ['leg raise sospensione', 'hanging leg raise'] },
  'hanging oblique knee raise': { canonicalIt: 'Sollevamento ginocchia oblique in sospensione', aliases: ['oblique knee raise'] },
  'hanging pike': { canonicalIt: 'Pike in sospensione', aliases: ['hanging pike'] },
  'high knee run': { canonicalIt: 'High knees', aliases: ['ginocchia alte'] },
  'hip thrust': { canonicalIt: 'Hip thrust', aliases: ['hip thrust'] },
  'hollow body hold': { canonicalIt: 'Hollow body hold', aliases: ['hollow hold'] },
  'hug knees to chest': { canonicalIt: 'Porta ginocchia al petto', aliases: ['knees to chest'] },
  'hyperextension': { canonicalIt: 'Iperextensione lombare', aliases: ['iperextensione'] },
  'inchworm': { canonicalIt: 'Inchworm', aliases: ['inchworm'] },
  'incline bench press': { canonicalIt: 'Panca inclinata', aliases: ['incline press', 'panca inclinata'] },
  'incline close-grip bench press': { canonicalIt: 'Panca inclinata stretta', aliases: ['incline close grip'] },
  'incline curl': { canonicalIt: 'Curl su panca inclinata', aliases: ['incline curl'] },
  'incline dumbbell bench press': { canonicalIt: 'Panca inclinata con manubri', aliases: ['incline dumbbell press'] },
  'incline dumbbell curl': { canonicalIt: 'Curl su panca inclinata con manubri', aliases: ['incline curl manubri'] },
  'incline dumbbell fly': { canonicalIt: 'Croci inclinate con manubri', aliases: ['incline fly manubri'] },
  'incline dumbbell hammer curl': { canonicalIt: 'Hammer curl su panca inclinata con manubri', aliases: ['incline hammer curl manubri'] },
  'incline dumbbell lateral raise': { canonicalIt: 'Alzate laterali su panca inclinata con manubri', aliases: ['incline lateral raise manubri'] },
  'incline dumbbell press': { canonicalIt: 'Panca inclinata con manubri', aliases: ['incline press manubri'] },
  'incline dumbbell row': { canonicalIt: 'Rematore su panca inclinata con manubri', aliases: ['incline row manubri'] },
  'incline dumbbell shoulder press': { canonicalIt: 'Shoulder press su panca inclinata con manubri', aliases: ['incline shoulder press manubri'] },
  'incline dumbbell shrinkage': { canonicalIt: 'Shoulder shrugs su panca inclinata con manubri', aliases: ['incline shrugs'] },
  'incline dumbbell triceps extension': { canonicalIt: 'Extension tricipiti su panca inclinata con manubri', aliases: ['incline triceps ext manubri'] },
  'incline hammer curl': { canonicalIt: 'Hammer curl su panca inclinata', aliases: ['incline hammer curl'] },
  'incline leg raise': { canonicalIt: 'Sollevamento gambe su panca inclinata', aliases: ['incline leg raise'] },
  'incline push-up': { canonicalIt: 'Push-up inclinato', aliases: ['push up inclinato'] },
  'incline push-up close-grip': { canonicalIt: 'Push-up inclinato presa stretta', aliases: ['incline close grip push up'] },
  'incline reverse crunch': { canonicalIt: 'Reverse crunch su panca inclinata', aliases: ['incline reverse crunch'] },
  'incline scapula push up': { canonicalIt: 'Scapula push-up su panca inclinata', aliases: ['incline scapula push up'] },
  'incline shoulder raise': { canonicalIt: 'Shoulder raise su panca inclinata', aliases: ['incline shoulder raise'] },
  'incline twisting sit-up': { canonicalIt: 'Sit-up twist su panca inclinata', aliases: ['incline twisting sit up'] },
  'inverted row': { canonicalIt: 'Rematore invertito', aliases: ['inverted row', 'australian pull up'] },
  'isometric wipers': { canonicalIt: 'Isometric wipers', aliases: ['wipers'] },
  'jackknife sit-up': { canonicalIt: 'Jackknife sit-up', aliases: ['jackknife'] },
  'jogging': { canonicalIt: 'Corsa lenta', aliases: ['jogging'] },
  'jump rope': { canonicalIt: 'Corda per saltare', aliases: ['corda', 'saltare la corda'] },
  'jump squat': { canonicalIt: 'Jump squat', aliases: ['squat salto'] },
  'kettlebell alternating press': { canonicalIt: 'Shoulder press alternato con kettlebell', aliases: ['kb press alternato'] },
  'kettlebell alternating renegade row': { canonicalIt: 'Renegade row alternato con kettlebell', aliases: ['kb renegade row'] },
  'kettlebell arnold press': { canonicalIt: 'Arnold press con kettlebell', aliases: ['kb arnold press'] },
  'kettlebell bench press': { canonicalIt: 'Panca piana con kettlebell', aliases: ['kb bench press'] },
  'kettlebell bent press': { canonicalIt: 'Bent press con kettlebell', aliases: ['kb bent press'] },
  'kettlebell bottoms up clean': { canonicalIt: 'Bottoms up clean con kettlebell', aliases: ['kb bottoms up clean'] },
  'kettlebell curl': { canonicalIt: 'Curl con kettlebell', aliases: ['kb curl'] },
  'kettlebell double alternating hang clean': { canonicalIt: 'Hang clean alternato doppio con kettlebell', aliases: ['kb hang clean'] },
  'kettlebell double clean': { canonicalIt: 'Double clean con kettlebell', aliases: ['kb double clean'] },
  'kettlebell double jerk': { canonicalIt: 'Double jerk con kettlebell', aliases: ['kb double jerk'] },
  'kettlebell double push press': { canonicalIt: 'Double push press con kettlebell', aliases: ['kb double push press'] },
  'kettlebell double snatch': { canonicalIt: 'Double snatch con kettlebell', aliases: ['kb double snatch'] },
  'kettlebell double windmill': { canonicalIt: 'Double windmill con kettlebell', aliases: ['kb double windmill'] },
  'kettlebell figure 8': { canonicalIt: 'Figure 8 con kettlebell', aliases: ['kb figure 8'] },
  'kettlebell front squat': { canonicalIt: 'Front squat con kettlebell', aliases: ['kb front squat'] },
  'kettlebell goblet squat': { canonicalIt: 'Goblet squat con kettlebell', aliases: ['kb goblet squat'] },
  'kettlebell hang clean': { canonicalIt: 'Hang clean con kettlebell', aliases: ['kb hang clean'] },
  'kettlebell high pull': { canonicalIt: 'High pull con kettlebell', aliases: ['kb high pull'] },
  'kettlebell jerk': { canonicalIt: 'Jerk con kettlebell', aliases: ['kb jerk'] },
  'kettlebell one arm clean': { canonicalIt: 'Clean monobraccio con kettlebell', aliases: ['kb one arm clean'] },
  'kettlebell one arm floor press': { canonicalIt: 'Floor press monobraccio con kettlebell', aliases: ['kb one arm floor press'] },
  'kettlebell one arm jerk': { canonicalIt: 'Jerk monobraccio con kettlebell', aliases: ['kb one arm jerk'] },
  'kettlebell one arm military press': { canonicalIt: 'Military press monobraccio con kettlebell', aliases: ['kb one arm press'] },
  'kettlebell one arm row': { canonicalIt: 'Rematore monobraccio con kettlebell', aliases: ['kb one arm row'] },
  'kettlebell one arm snatch': { canonicalIt: 'Snatch monobraccio con kettlebell', aliases: ['kb one arm snatch'] },
  'kettlebell pirate ships': { canonicalIt: 'Pirate ships con kettlebell', aliases: ['kb pirate ships'] },
  'kettlebell pistol squat': { canonicalIt: 'Pistol squat con kettlebell', aliases: ['kb pistol squat'] },
  'kettlebell push press': { canonicalIt: 'Push press con kettlebell', aliases: ['kb push press'] },
  'kettlebell seated press': { canonicalIt: 'Shoulder press seduto con kettlebell', aliases: ['kb seated press'] },
  'kettlebell seated shoulder press': { canonicalIt: 'Shoulder press seduto con kettlebell', aliases: ['kb seated shoulder press'] },
  'kettlebell seesaw press': { canonicalIt: 'Seesaw press con kettlebell', aliases: ['kb seesaw press'] },
  'kettlebell sit-up': { canonicalIt: 'Sit-up con kettlebell', aliases: ['kb sit up'] },
  'kettlebell snatch': { canonicalIt: 'Snatch con kettlebell', aliases: ['kb snatch'] },
  'kettlebell sumo deadlift high pull': { canonicalIt: 'Sumo deadlift high pull con kettlebell', aliases: ['kb sumo high pull'] },
  'kettlebell swing': { canonicalIt: 'Kettlebell swing', aliases: ['kb swing', 'swing'] },
  'kettlebell thruster': { canonicalIt: 'Thruster con kettlebell', aliases: ['kb thruster'] },
  'kettlebell turkish get up': { canonicalIt: 'Turkish get-up con kettlebell', aliases: ['kb get up', 'turkish get up'] },
  'kettlebell two arm swing': { canonicalIt: 'Two arm swing con kettlebell', aliases: ['kb two arm swing'] },
  'kettlebell windmill': { canonicalIt: 'Windmill con kettlebell', aliases: ['kb windmill'] },
  'kick out': { canonicalIt: 'Kick out', aliases: ['kick out'] },
  'kipping muscle up': { canonicalIt: 'Kipping muscle-up', aliases: ['muscle up kipping'] },
  'knee touch crunch': { canonicalIt: 'Crunch tocchi ginocchia', aliases: ['knee touch crunch'] },
  'landmine 180': { canonicalIt: 'Landmine 180', aliases: ['landmine rotation'] },
  'landmine anti-rotational hold': { canonicalIt: 'Landmine anti-rotation hold', aliases: ['landmine anti rot'] },
  'landmine lateral raise': { canonicalIt: 'Alzate laterali al landmine', aliases: ['landmine lateral raise'] },
  'landmine press': { canonicalIt: 'Landmine press', aliases: ['landmine shoulder press'] },
  'landmine row': { canonicalIt: 'Rematore al landmine', aliases: ['landmine row'] },
  'landmine squat': { canonicalIt: 'Squat al landmine', aliases: ['landmine squat'] },
  'lat pulldown': { canonicalIt: 'Lat pulldown', aliases: ['pulldown', 'trazione al cavo'] },
  'lateral raise': { canonicalIt: 'Alzate laterali', aliases: ['alzate laterali', 'lateral raise'] },
  'leg extension': { canonicalIt: 'Leg extension', aliases: ['estensione gambe', 'leg extension'] },
  'leg press': { canonicalIt: 'Leg press', aliases: ['pressa', 'leg press'] },
  'leg raise': { canonicalIt: 'Sollevamento gambe', aliases: ['leg raise'] },
  'lever alternate leg extension': { canonicalIt: 'Leg extension alternata al macchinario', aliases: ['alternate leg extension'] },
  'lever assisted chin-up': { canonicalIt: 'Chin-up assistito al macchinario', aliases: ['assisted chin up'] },
  'lever back extension': { canonicalIt: 'Iperextensione lombare al macchinario', aliases: ['back extension machine'] },
  'lever bent over row': { canonicalIt: 'Rematore piegato al macchinario', aliases: ['machine bent over row'] },
  'lever chest press': { canonicalIt: 'Chest press al macchinario', aliases: ['chest press machine'] },
  'lever front pulldown': { canonicalIt: 'Pulldown frontale al macchinario', aliases: ['front pulldown machine'] },
  'lever grip machine': { canonicalIt: 'Grip machine', aliases: ['machine grip'] },
  'lever hammer grip preacher curl': { canonicalIt: 'Hammer curl su panca Scott al macchinario', aliases: ['machine hammer preacher curl'] },
  'lever high row': { canonicalIt: 'High row al macchinario', aliases: ['machine high row'] },
  'lever hip extension': { canonicalIt: 'Hip extension al macchinario', aliases: ['machine hip extension'] },
  'lever incline chest press': { canonicalIt: 'Chest press inclinata al macchinario', aliases: ['incline chest press machine'] },
  'lever kneeling leg curl': { canonicalIt: 'Leg curl in ginocchio al macchinario', aliases: ['kneeling leg curl'] },
  'lever lateral raise': { canonicalIt: 'Alzate laterali al macchinario', aliases: ['machine lateral raise'] },
  'lever leg extension': { canonicalIt: 'Leg extension al macchinario', aliases: ['machine leg extension'] },
  'lever lying leg curl': { canonicalIt: 'Leg curl disteso al macchinario', aliases: ['lying leg curl machine'] },
  'lever military press': { canonicalIt: 'Military press al macchinario', aliases: ['machine military press'] },
  'lever preacher curl': { canonicalIt: 'Curl su panca Scott al macchinario', aliases: ['machine preacher curl'] },
  'lever pullover': { canonicalIt: 'Pullover al macchinario', aliases: ['machine pullover'] },
  'lever reverse hyperextension': { canonicalIt: 'Reverse hyperextension al macchinario', aliases: ['reverse hyper machine'] },
  'lever reverse t-bar row': { canonicalIt: 'Reverse T-bar row al macchinario', aliases: ['reverse tbar row'] },
  'lever rowing': { canonicalIt: 'Rematore al macchinario', aliases: ['machine row'] },
  'lever seated calf raise': { canonicalIt: 'Sollevamenti polpacci seduto al macchinario', aliases: ['seated calf raise machine'] },
  'lever seated chest press': { canonicalIt: 'Chest press seduto al macchinario', aliases: ['seated chest press machine'] },
  'lever seated crunch': { canonicalIt: 'Crunch seduto al macchinario', aliases: ['seated crunch machine'] },
  'lever seated dip': { canonicalIt: 'Dip seduto al macchinario', aliases: ['seated dip machine'] },
  'lever seated fly': { canonicalIt: 'Croci seduto al macchinario', aliases: ['seated fly machine'] },
  'lever seated good morning': { canonicalIt: 'Good morning seduto al macchinario', aliases: ['seated good morning machine'] },
  'lever seated hip abduction': { canonicalIt: 'Adduttori al macchinario', aliases: ['hip abduction machine'] },
  'lever seated hip adduction': { canonicalIt: 'Adduttori al macchinario', aliases: ['hip adduction machine'] },
  'lever seated leg curl': { canonicalIt: 'Leg curl seduto al macchinario', aliases: ['seated leg curl machine'] },
  'lever seated row': { canonicalIt: 'Rematore seduto al macchinario', aliases: ['seated row machine'] },
  'lever seated shoulder press': { canonicalIt: 'Shoulder press seduto al macchinario', aliases: ['seated shoulder press machine'] },
  'lever shoulder press': { canonicalIt: 'Shoulder press al macchinario', aliases: ['shoulder press machine'] },
  'lever shrug': { canonicalIt: 'Shrug al macchinario', aliases: ['machine shrug'] },
  'lever standing calf raise': { canonicalIt: 'Sollevamenti polpacci in piedi al macchinario', aliases: ['standing calf raise machine'] },
  'lever t-bar row': { canonicalIt: 'T-bar row al macchinario', aliases: ['tbar row machine'] },
  'lever triceps extension': { canonicalIt: 'Extension tricipiti al macchinario', aliases: ['machine triceps extension'] },
  'lever unilateral row': { canonicalIt: 'Rematore unilaterale al macchinario', aliases: ['unilateral row machine'] },
  'lying leg curl': { canonicalIt: 'Leg curl disteso', aliases: ['leg curl'] },
  'machine seated crunch': { canonicalIt: 'Crunch seduto al macchinario', aliases: ['seated crunch machine'] },
  'mountain climber': { canonicalIt: 'Mountain climber', aliases: ['climber'] },
  'muscle up': { canonicalIt: 'Muscle-up', aliases: ['muscle up'] },
  'narrow push-up': { canonicalIt: 'Push-up stretto', aliases: ['push up stretto'] },
  'neck bridge supine': { canonicalIt: 'Neck bridge supino', aliases: ['neck bridge'] },
  'oblique crunches': { canonicalIt: 'Crunch obliqui', aliases: ['oblique crunch'] },
  'one arm against wall': { canonicalIt: 'One arm against wall', aliases: ['one arm wall'] },
  'one arm chin-up': { canonicalIt: 'Chin-up monobraccio', aliases: ['one arm chin up'] },
  'one arm dip': { canonicalIt: 'Dip monobraccio', aliases: ['one arm dip'] },
  'one arm dumbbell preacher curl': { canonicalIt: 'Curl su panca Scott monobraccio con manubrio', aliases: ['one arm preacher curl'] },
  'one arm lat pulldown': { canonicalIt: 'Lat pulldown monobraccio', aliases: ['one arm pulldown'] },
  'one arm pull-up': { canonicalIt: 'Pull-up monobraccio', aliases: ['one arm pull up'] },
  'one arm push-up': { canonicalIt: 'Push-up monobraccio', aliases: ['one arm push up'] },
  'one leg squat': { canonicalIt: 'Squat monogamba', aliases: ['pistol squat', 'one leg squat'] },
  'otis-up': { canonicalIt: 'Otis-up', aliases: ['otis up'] },
  'overhead triceps extension': { canonicalIt: 'Extension tricipiti sopra testa', aliases: ['overhead triceps ext'] },
  'parallel bar dip': { canonicalIt: 'Dip alle parallele', aliases: ['dip parallele'] },
  'pike push-up': { canonicalIt: 'Pike push-up', aliases: ['pike push up'] },
  'plank': { canonicalIt: 'Plank', aliases: ['plank', 'planche'] },
  'power clean': { canonicalIt: 'Power clean', aliases: ['power clean'] },
  'power snatch': { canonicalIt: 'Power snatch', aliases: ['power snatch'] },
  'preacher curl': { canonicalIt: 'Curl su panca Scott', aliases: ['preacher curl', 'curl scott'] },
  'press sit-up': { canonicalIt: 'Press sit-up', aliases: ['press sit up'] },
  'pull through': { canonicalIt: 'Pull-through', aliases: ['pull through'] },
  'pull-up': { canonicalIt: 'Pull-up', aliases: ['pull up', 'trazione'] },
  'push-up': { canonicalIt: 'Push-up', aliases: ['push up', 'piegamento'] },
  'push-up plus': { canonicalIt: 'Push-up plus', aliases: ['push up plus'] },
  'reverse crunch': { canonicalIt: 'Reverse crunch', aliases: ['reverse crunch'] },
  'reverse fly': { canonicalIt: 'Reverse fly', aliases: ['rear delt fly'] },
  'reverse grip lat pulldown': { canonicalIt: 'Lat pulldown presa inversa', aliases: ['pulldown inverso'] },
  'romanian deadlift': { canonicalIt: 'Romanian deadlift', aliases: ['rdl', 'stiff rumeno'] },
  'rope climb': { canonicalIt: 'Salita alla corda', aliases: ['rope climb'] },
  'rowing': { canonicalIt: 'Rowing', aliases: ['remo'] },
  'russian twist': { canonicalIt: 'Russian twist', aliases: ['russian twist'] },
  'scapular pull-up': { canonicalIt: 'Scapular pull-up', aliases: ['scapular pull up'] },
  'seated barbell military press': { canonicalIt: 'Military press seduto con bilanciere', aliases: ['seated military press'] },
  'seated barbell shoulder press': { canonicalIt: 'Shoulder press seduto con bilanciere', aliases: ['seated shoulder press bb'] },
  'seated cable row': { canonicalIt: 'Rematore seduto al cavo', aliases: ['seated row cavo'] },
  'seated calf raise': { canonicalIt: 'Sollevamenti polpacci seduto', aliases: ['seated calf raise'] },
  'seated chest press': { canonicalIt: 'Chest press seduto', aliases: ['seated chest press'] },
  'seated close-grip concentration barbell curl': { canonicalIt: 'Curl concentrazione stretto seduto con bilanciere', aliases: ['seated close grip curl bb'] },
  'seated dumbbell curl': { canonicalIt: 'Curl seduto con manubri', aliases: ['seated dumbbell curl'] },
  'seated dumbbell inner biceps curl': { canonicalIt: 'Curl bicipiti interno seduto con manubri', aliases: ['seated inner curl'] },
  'seated dumbbell lateral raise': { canonicalIt: 'Alzate laterali seduto con manubri', aliases: ['seated lateral raise db'] },
  'seated dumbbell overhead triceps extension': { canonicalIt: 'Extension tricipiti sopra testa seduto con manubri', aliases: ['seated overhead triceps ext db'] },
  'seated dumbbell palm-up wrist curl': { canonicalIt: 'Wrist curl palma su seduto con manubri', aliases: ['seated wrist curl db'] },
  'seated dumbbell press': { canonicalIt: 'Shoulder press seduto con manubri', aliases: ['seated dumbbell press'] },
  'seated dumbbell reverse wrist curl': { canonicalIt: 'Reverse wrist curl seduto con manubri', aliases: ['seated reverse wrist curl'] },
  'seated leg curl': { canonicalIt: 'Leg curl seduto', aliases: ['seated leg curl'] },
  'seated leg raise': { canonicalIt: 'Sollevamento gambe seduto', aliases: ['seated leg raise'] },
  'seated military press': { canonicalIt: 'Military press seduto', aliases: ['seated military press'] },
  'seated shoulder press': { canonicalIt: 'Shoulder press seduto', aliases: ['seated shoulder press'] },
  'seated side lateral raise': { canonicalIt: 'Alzate laterali seduto', aliases: ['seated side lateral raise'] },
  'seated triceps press': { canonicalIt: 'Press tricipiti seduto', aliases: ['seated triceps press'] },
  'shoulder press': { canonicalIt: 'Shoulder press', aliases: ['spinte spalle', 'military press'] },
  'shoulder tap push-up': { canonicalIt: 'Push-up con tocchi alle spalle', aliases: ['shoulder tap push up'] },
  'shrug': { canonicalIt: 'Shrug', aliases: ['shrug'] },
  'side bridge': { canonicalIt: 'Side bridge', aliases: ['side plank'] },
  'side lying leg raise': { canonicalIt: 'Sollevamento gambe laterale', aliases: ['side leg raise'] },
  'side plank': { canonicalIt: 'Side plank', aliases: ['plank laterale'] },
  'single arm cable crossover': { canonicalIt: 'Crossover monobraccio al cavo', aliases: ['single arm crossover'] },
  'single leg calf raise': { canonicalIt: 'Sollevamento polpacci monogamba', aliases: ['single leg calf raise'] },
  'single leg deadlift': { canonicalIt: 'Stacco monogamba', aliases: ['single leg deadlift'] },
  'single leg glute bridge': { canonicalIt: 'Glute bridge monogamba', aliases: ['single leg glute bridge'] },
  'single leg hip thrust': { canonicalIt: 'Hip thrust monogamba', aliases: ['single leg hip thrust'] },
  'single leg press': { canonicalIt: 'Leg press monogamba', aliases: ['single leg press'] },
  'single leg squat': { canonicalIt: 'Squat monogamba', aliases: ['single leg squat'] },
  'sit-up': { canonicalIt: 'Sit-up', aliases: ['sit up'] },
  'sissy squat': { canonicalIt: 'Sissy squat', aliases: ['sissy squat'] },
  'skater hop': { canonicalIt: 'Skater hop', aliases: ['skater'] },
  'ski ergometer': { canonicalIt: 'Ski ergometer', aliases: ['ski erg'] },
  'skull crusher': { canonicalIt: 'Skullcrusher', aliases: ['skull crusher'] },
  'sled 45 degrees leg press': { canonicalIt: 'Leg press a 45° con slitta', aliases: ['sled leg press'] },
  'smith bench press': { canonicalIt: 'Panca piana al multipower', aliases: ['panca multipower', 'smith bench press'] },
  'smith close-grip bench press': { canonicalIt: 'Panca stretta al multipower', aliases: ['smith close grip bench'] },
  'smith deadlift': { canonicalIt: 'Stacco da terra al multipower', aliases: ['smith deadlift'] },
  'smith decline bench press': { canonicalIt: 'Panca declinata al multipower', aliases: ['smith decline bench'] },
  'smith front squat': { canonicalIt: 'Front squat al multipower', aliases: ['smith front squat'] },
  'smith hack squat': { canonicalIt: 'Hack squat al multipower', aliases: ['smith hack squat'] },
  'smith incline bench press': { canonicalIt: 'Panca inclinata al multipower', aliases: ['smith incline bench'] },
  'smith machine back squat': { canonicalIt: 'Squat al multipower', aliases: ['squat multipower'] },
  'smith machine bicep curl': { canonicalIt: 'Curl bicipiti al multipower', aliases: ['smith curl'] },
  'smith machine calf raise': { canonicalIt: 'Sollevamenti polpacci al multipower', aliases: ['smith calf raise'] },
  'smith machine decline close-grip bench press': { canonicalIt: 'Panca declinata stretta al multipower', aliases: ['smith decline close grip'] },
  'smith machine drag curl': { canonicalIt: 'Drag curl al multipower', aliases: ['smith drag curl'] },
  'smith machine hang power clean': { canonicalIt: 'Hang power clean al multipower', aliases: ['smith hang power clean'] },
  'smith machine incline tricep extension': { canonicalIt: 'Extension tricipiti inclinata al multipower', aliases: ['smith incline triceps ext'] },
  'smith machine lunge': { canonicalIt: 'Affondi al multipower', aliases: ['smith lunge'] },
  'smith machine overhead press': { canonicalIt: 'Spinte sopra testa al multipower', aliases: ['smith overhead press'] },
  'smith machine pistol squat': { canonicalIt: 'Pistol squat al multipower', aliases: ['smith pistol squat'] },
  'smith machine reverse calf raises': { canonicalIt: 'Reverse calf raise al multipower', aliases: ['smith reverse calf raise'] },
  'smith machine reverse drag curl': { canonicalIt: 'Drag curl inverso al multipower', aliases: ['smith reverse drag curl'] },
  'smith machine shrug': { canonicalIt: 'Shrug al multipower', aliases: ['smith shrug'] },
  'smith machine squat': { canonicalIt: 'Squat al multipower', aliases: ['squat multipower'] },
  'smith machine stiff leg deadlift': { canonicalIt: 'Stiff leg deadlift al multipower', aliases: ['smith stiff leg deadlift'] },
  'smith machine upright row': { canonicalIt: 'Upright row al multipower', aliases: ['smith upright row'] },
  'smith machine wrist curl': { canonicalIt: 'Wrist curl al multipower', aliases: ['smith wrist curl'] },
  'smith reverse calf raises': { canonicalIt: 'Reverse calf raise al multipower', aliases: ['smith reverse calf raise'] },
  'smith shoulder press': { canonicalIt: 'Shoulder press al multipower', aliases: ['smith shoulder press'] },
  'smith squat': { canonicalIt: 'Squat al multipower', aliases: ['squat multipower'] },
  'snatch': { canonicalIt: 'Snatch', aliases: ['snatch'] },
  'spider curl': { canonicalIt: 'Spider curl', aliases: ['spider curl'] },
  'spiderman push-up': { canonicalIt: 'Spiderman push-up', aliases: ['spiderman push up'] },
  'sprint': { canonicalIt: 'Sprint', aliases: ['sprint'] },
  'squat': { canonicalIt: 'Squat', aliases: ['squat', 'accosciata'] },
  'stair climber': { canonicalIt: 'Stair climber', aliases: ['scala'] },
  'standing barbell calf raise': { canonicalIt: 'Sollevamenti polpacci in piedi con bilanciere', aliases: ['standing calf raise bb'] },
  'standing barbell press': { canonicalIt: 'Spinte in piedi con bilanciere', aliases: ['standing press bb'] },
  'standing barbell shoulder press': { canonicalIt: 'Shoulder press in piedi con bilanciere', aliases: ['standing shoulder press bb'] },
  'standing bradford press': { canonicalIt: 'Bradford press in piedi', aliases: ['bradford press'] },
  'standing calf raises': { canonicalIt: 'Sollevamenti polpacci in piedi', aliases: ['standing calf raise'] },
  'standing dumbbell calf raise': { canonicalIt: 'Sollevamenti polpacci in piedi con manubri', aliases: ['standing calf raise db'] },
  'standing dumbbell reverse curl': { canonicalIt: 'Curl inverso in piedi con manubri', aliases: ['standing reverse curl db'] },
  'standing dumbbell shoulder press': { canonicalIt: 'Shoulder press in piedi con manubri', aliases: ['standing shoulder press db'] },
  'standing dumbbell triceps extension': { canonicalIt: 'Extension tricipiti in piedi con manubri', aliases: ['standing triceps ext db'] },
  'standing dumbbell upright row': { canonicalIt: 'Upright row in piedi con manubri', aliases: ['standing upright row db'] },
  'standing hamstring and calf stretch': { canonicalIt: 'Stretch ischiocrurali e polpacci in piedi', aliases: ['hamstring calf stretch'] },
  'standing lateral stretch': { canonicalIt: 'Stretch laterale in piedi', aliases: ['lateral stretch'] },
  'standing leg curl': { canonicalIt: 'Leg curl in piedi', aliases: ['standing leg curl'] },
  'standing military press': { canonicalIt: 'Military press in piedi', aliases: ['standing military press'] },
  'standing overhead barbell triceps extension': { canonicalIt: 'Extension tricipiti sopra testa in piedi con bilanciere', aliases: ['standing overhead triceps ext bb'] },
  'standing palm-in one-arm dumbbell press': { canonicalIt: 'Shoulder press monobraccio palma inwards con manubrio', aliases: ['standing one arm press db'] },
  'standing rope crunch': { canonicalIt: 'Crunch con fune in piedi', aliases: ['standing rope crunch'] },
  'standing shoulder press': { canonicalIt: 'Shoulder press in piedi', aliases: ['standing shoulder press'] },
  'standing wrist curl': { canonicalIt: 'Wrist curl in piedi', aliases: ['standing wrist curl'] },
  'star jump': { canonicalIt: 'Star jump', aliases: ['salto stella'] },
  'stationary bike': { canonicalIt: 'Cyclette', aliases: ['cyclette', 'bike'] },
  'step-up': { canonicalIt: 'Step-up', aliases: ['step up'] },
  'stiff leg deadlift': { canonicalIt: 'Stiff leg deadlift', aliases: ['stiff leg dl'] },
  'straight bar bench mid row': { canonicalIt: 'Rematore medio con barra dritta', aliases: ['mid row'] },
  'straight-leg deadlift': { canonicalIt: 'Stiff-leg deadlift', aliases: ['stiff leg deadlift'] },
  'sumo deadlift': { canonicalIt: 'Sumo deadlift', aliases: ['sumo deadlift'] },
  'superman': { canonicalIt: 'Superman', aliases: ['superman'] },
  't-bar row': { canonicalIt: 'T-bar row', aliases: ['tbar row'] },
  'thruster': { canonicalIt: 'Thruster', aliases: ['thruster'] },
  'toes to bar': { canonicalIt: 'Toes to bar', aliases: ['tocca la sbarra'] },
  'treadmill': { canonicalIt: 'Tapis roulant', aliases: ['tapis roulant', 'treadmill'] },
  'tricep dip': { canonicalIt: 'Dip tricipiti', aliases: ['triceps dip'] },
  'tricep pushdown': { canonicalIt: 'Pushdown tricipiti', aliases: ['triceps pushdown', 'pushdown'] },
  'triceps dip': { canonicalIt: 'Dip tricipiti', aliases: ['tricep dip'] },
  'triceps extension': { canonicalIt: 'Extension tricipiti', aliases: ['triceps extension'] },
  'triceps pushdown': { canonicalIt: 'Pushdown tricipiti', aliases: ['pushdown tricipiti'] },
  'tuck crunch': { canonicalIt: 'Tuck crunch', aliases: ['tuck crunch'] },
  'twist': { canonicalIt: 'Twist', aliases: ['rotazione busto'] },
  'upright row': { canonicalIt: 'Upright row', aliases: ['upright row'] },
  'v-sit': { canonicalIt: 'V-sit', aliases: ['v sit'] },
  'wide-grip lat pulldown': { canonicalIt: 'Lat pulldown presa larga', aliases: ['pulldown largo'] },
  'wide-grip pull-up': { canonicalIt: 'Pull-up presa larga', aliases: ['pull up largo'] },
  'wide-grip upright row': { canonicalIt: 'Upright row presa larga', aliases: ['upright row largo'] },
  'windmill': { canonicalIt: 'Windmill', aliases: ['windmill'] },
  'wrist curl': { canonicalIt: 'Wrist curl', aliases: ['curl polsi'] },
  'zottman curl': { canonicalIt: 'Zottman curl', aliases: ['zottman curl'] }
};

function normalizeName(name) {
  return String(name || '').toLowerCase().trim();
}

function main() {
  if (!fs.existsSync(DATASET_PATH)) {
    console.error('Dataset non trovato:', DATASET_PATH);
    process.exit(1);
  }

  const raw = JSON.parse(fs.readFileSync(DATASET_PATH, 'utf8'));

  const catalog = {
    exercises: raw.map((ex) => ({
      id: String(ex.id || ''),
      name: String(ex.name || ''),
      bodyPart: String(ex.body_part || ''),
      target: String(ex.target || ''),
      secondaryMuscles: Array.isArray(ex.secondary_muscles) ? ex.secondary_muscles.map(String) : [],
      equipment: String(ex.equipment || ''),
      instructionsIt: String((ex.instructions && ex.instructions.it) || ''),
      instructionStepsIt: Array.isArray(ex.instruction_steps && ex.instruction_steps.it)
        ? ex.instruction_steps.it.map(String)
        : [],
      image: String(ex.image || ''),
      video: String(ex.video || '')
    })).filter((ex) => ex.id && ex.name)
  };

  const aliases = {};
  catalog.exercises.forEach((ex) => {
    const key = normalizeName(ex.name);
    const mapping = ITALIAN_MAPPINGS[key];
    aliases[ex.id] = {
      canonicalIt: mapping ? mapping.canonicalIt : '',
      aliases: mapping ? mapping.aliases : []
    };
  });

  fs.writeFileSync(CATALOG_OUT, JSON.stringify(catalog, null, 2));
  fs.writeFileSync(ALIASES_OUT, JSON.stringify(aliases, null, 2));

  const withItalian = Object.values(aliases).filter((a) => a.canonicalIt).length;
  console.log(`Catalogo generato: ${catalog.exercises.length} esercizi`);
  console.log(`Esercizi con nome italiano curato: ${withItalian}`);
  console.log('Output:', CATALOG_OUT, ALIASES_OUT);
}

main();
